// MakAir
//
// Copyright: 2020, Makers For Life
// License: Public Domain License

pub const DISPLAY_WINDOW_SIZE_WIDTH: u32 = 800;
pub const DISPLAY_WINDOW_SIZE_HEIGHT: u32 = 480;

pub const DISPLAY_GRAPH_OFFSET_WIDTH: u32 = 42;
pub const DISPLAY_GRAPH_OFFSET_HEIGHT: u32 = 260;

pub const DISPLAY_WIDGET_SPACING_FROM_BOTTOM: f64 = 18.0;
pub const DISPLAY_WIDGET_SIZE_WIDTH: f64 = 116.0;
pub const DISPLAY_WIDGET_SIZE_HEIGHT: f64 = 72.0;
pub const DISPLAY_WIDGET_SIZE_SPACING: f64 = 14.0;

pub const GRAPH_DRAW_SPACING_FROM_BOTTOM: f64 = 140.0;
pub const GRAPH_DRAW_SECONDS: usize = 9;
pub const GRAPH_DRAW_RANGE_LOW: i32 = 0;
pub const GRAPH_DRAW_RANGE_HIGH: i32 = 90;
pub const GRAPH_DRAW_MARGIN_TOP: u32 = 0;
pub const GRAPH_DRAW_MARGIN_BOTTOM: u32 = 10;
pub const GRAPH_DRAW_MARGIN_LEFT: u32 = 0;
pub const GRAPH_DRAW_MARGIN_RIGHT: u32 = 0;
pub const GRAPH_DRAW_LINE_SIZE: u32 = 2;
pub const GRAPH_DRAW_LABEL_WIDTH: u32 = 28;
