// MakAir
//
// Copyright: 2020, Makers For Life
// License: Public Domain License

pub const RUNTIME_VERSION: &'static str = env!("CARGO_PKG_VERSION");

pub const DISPLAY_WINDOW_SIZE_WIDTH: u32 = 800;
pub const DISPLAY_WINDOW_SIZE_HEIGHT: u32 = 480;

pub const DISPLAY_GRAPH_OFFSET_WIDTH: u32 = 42;
pub const DISPLAY_GRAPH_OFFSET_HEIGHT: u32 = 220;

pub const DISPLAY_WIDGET_SPACING_FROM_BOTTOM: f64 = 18.0;
pub const DISPLAY_WIDGET_SIZE_WIDTH: f64 = 116.0;
pub const DISPLAY_WIDGET_SIZE_HEIGHT: f64 = 72.0;
pub const DISPLAY_WIDGET_SIZE_SPACING: f64 = 14.0;

pub const BRANDING_WIDTH: u32 = 121;
pub const BRANDING_HEIGHT: u32 = 45;
pub const BRANDING_IMAGE_MARGIN_TOP: f64 = 22.0;
pub const BRANDING_IMAGE_MARGIN_LEFT: f64 = 26.0;
pub const BRANDING_TEXT_MARGIN_TOP: f64 = 52.0;
pub const BRANDING_TEXT_MARGIN_LEFT: f64 = 82.0;

pub const TELEMETRY_POINTS_PER_SECOND: usize = 10 * 100;

pub const GRAPH_DRAW_SPACING_FROM_BOTTOM: f64 = 120.0;
pub const GRAPH_DRAW_SECONDS: usize = 9;
pub const GRAPH_DRAW_RANGE_LOW: i32 = 0;
pub const GRAPH_DRAW_RANGE_HIGH: i32 = 90;
pub const GRAPH_DRAW_MARGIN_TOP: u32 = 0;
pub const GRAPH_DRAW_MARGIN_BOTTOM: u32 = 10;
pub const GRAPH_DRAW_MARGIN_LEFT: u32 = 0;
pub const GRAPH_DRAW_MARGIN_RIGHT: u32 = 0;
pub const GRAPH_DRAW_LINE_SIZE: u32 = 2;
pub const GRAPH_DRAW_LABEL_WIDTH: u32 = 28;
pub const GRAPH_NUMBER_OF_POINTS: usize = GRAPH_DRAW_SECONDS * TELEMETRY_POINTS_PER_SECOND;
